import { Component } from '@angular/core';
import {FormBuilder, FormGroup, Validators} from "@angular/forms";
import {ProjectModel} from "../../model/ProjectModel";

@Component({
  selector: 'app-add-project-form',
  templateUrl: './add-project-form.component.html',
  styleUrls: ['./add-project-form.component.scss']
})
export class AddProjectFormComponent {
  public projectForm!: FormGroup;
  public project!: ProjectModel;

  constructor(private formBuilder: FormBuilder) { }

  ngOnInit() {
    this.projectForm = this.formBuilder.group({
      name: ['', Validators.required],
      contexte: ['', Validators.required],
      but: ['', Validators.required],
      justification: ['', Validators.required],
      apportLocal: ['', Validators.required],
      devis: ['', Validators.required],
      planning: ['', Validators.required],
      location: ['', Validators.required],
      country: ['', Validators.required],
      start: ['', Validators.required],
      end: ['', Validators.required],
      userId: ['', Validators.required],
      beneficiary: ['', Validators.required],
      result: ['', Validators.required],
      impact: ['', Validators.required],
      imageUrl: ['', Validators.required]
    });
  }

  public onSubmit() {
    if (this.projectForm.valid) {
      this.project = new ProjectModel(
        this.projectForm.value.name,
        this.projectForm.value.contexte,
        this.projectForm.value.but,
        this.projectForm.value.justification,
        this.projectForm.value.apportLocal,
        this.projectForm.value.devis,
        this.projectForm.value.planning,
        this.projectForm.value.location,
        this.projectForm.value.country,
        this.projectForm.value.start,
        this.projectForm.value.end,
        this.projectForm.value.userId,
        this.projectForm.value.beneficiary,
        this.projectForm.value.result,
        this.projectForm.value.impact,
        '',    // id will be generated by the server
        'draft', // default status for a new project
        this.projectForm.value.imageUrl
      );
      // Call the API to create the project
    }
  }
}
