import {Component, Inject} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from "@angular/forms";
import {ProjectModel} from "../../model/ProjectModel";
import {MAT_DIALOG_DATA} from "@angular/material/dialog";

@Component({
  selector: 'app-add-project-form',
  templateUrl: './add-project-form.component.html',
  styleUrls: ['./add-project-form.component.scss']
})
export class AddProjectFormComponent {
  public projectForm!: FormGroup;
  public project!: ProjectModel;
  filesData: any[] = [];

  // @ts-ignore
  constructor(private formBuilder: FormBuilder , @Inject(MAT_DIALOG_DATA) private data: ProjectModel) { }

  ngOnInit() {
    this.projectForm = this.formBuilder.group({
      name: [this.data.name, Validators.required],
      contexte: [ this.data.contexte, Validators.required],
      but: [ this.data.but, Validators.required],
      justification: [ this.data.justification, Validators.required],
      apportLocal: [ this.data.apportLocal, Validators.required],
      devis: [this.data.devis, Validators.required],
      planning: [this.data.planning, Validators.required],
      location: [this.data.location, Validators.required],
      country: [this.data.country, Validators.required],
      start: [this.data.start, Validators.required],
      end: [this.data.end, Validators.required],
      userId: [this.data.userId, Validators.required],
      beneficiary: [this.data.beneficiary, Validators.required],
      result: [ this.data.result, Validators.required],
      impact: [ this.data.impact, Validators.required],
      imageUrl: [ this.data.imageUrl, Validators.required],
      image1: ['', Validators.required],
      image2: ['', Validators.required],
      image3: ['', Validators.required],
      image4: ['', Validators.required],
      image5: ['', Validators.required],
    });
  }

  public onSubmit() {
    if (this.projectForm.valid) {
      this.project = new ProjectModel(
        this.projectForm.value.name,
        this.projectForm.value.contexte,
        this.projectForm.value.but,
        this.projectForm.value.justification,
        this.projectForm.value.apportLocal,
        this.projectForm.value.devis,
        this.projectForm.value.planning,
        this.projectForm.value.location,
        this.projectForm.value.country,
        this.projectForm.value.start,
        this.projectForm.value.end,
        this.projectForm.value.userId,
        this.projectForm.value.beneficiary,
        this.projectForm.value.result,
        this.projectForm.value.impact,
        '',    // id will be generated by the server
        'draft', // default status for a new project
        this.projectForm.value.imageUrl,
        this.projectForm.value.image1,
        this.projectForm.value.image2,
        this.projectForm.value.image3,
        this.projectForm.value.image4,
        this.projectForm.value.image5
      );
      // Call the API to create the project
    }
  }

  receiveFileData($event: { id: string; fileData$: File }) {
    this.filesData.push($event)

  }
}
